apiVersion: v1
kind: Secret
metadata:
  name: lphajir-secrets
  namespace: lphajir
type: Opaque
stringData:
  # Segredo de aplicação (exemplo forte - recomendo trocar em produção)
  APP_SECRET: "pH7G!tY9qL2@wR5zC8#nV1bK4^xM6sD3?jP0fQ7uT9yW2"

